# Configuración High Quality - RTX 4070 Ti, RTX 3080 (10-12GB VRAM)
# Balance entre calidad y rendimiento para GPUs de gama media-alta

hardware:
  gpu_memory_limit: 10000  # MB - Dejar buffer de 2GB
  cpu_cores: 12
  batch_size: 8
  mixed_precision: true
  flash_attention: true
  tensorrt_optimization: true
  torch_compile: true

video:
  max_resolution: [2560, 1440]  # 1440p
  target_fps: 20
  temporal_sampling: 6
  quality_preset: "high"
  codec: "h264"
  max_duration: 90  # segundos

attention:
  # Canal A - Atención Espaciotemporal Global
  channel_a:
    model: "mvit_v2_s"
    backbone: "mvit_v2_s_16x2_224"
    attention_type: "gmar"
    spatial_resolution: [224, 224]
    temporal_window: 12
    attention_heads: 12
    flash_attention: true
    gradient_checkpointing: false
    
  # Canal B - Atención por Objetos
  channel_b:
    detection_model: "deformable_detr"
    tracking_model: "trackformer"
    object_classes: ["person", "vehicle", "animal", "object"]
    confidence_threshold: 0.6
    nms_threshold: 0.5
    max_objects: 15
    tracking_persistence: 0.7

visualization:
  # Canal A - Sombras azules semitransparentes
  channel_a_style:
    color: [0, 100, 255]  # Azul
    alpha: 0.6
    blur_radius: 3
    heatmap_smoothing: 0.7
    
  # Canal B - Sombras de colores por objeto
  channel_b_style:
    colors:
      person: [255, 0, 0]      # Rojo
      vehicle: [0, 255, 0]     # Verde
      animal: [255, 165, 0]    # Naranja
      object: [128, 0, 128]    # Púrpura
    alpha: 0.7
    blur_radius: 2
    object_tracking: true
    
  # Configuración general
  output_format: "gif"
  output_quality: 90
  frame_rate: 8
  loop: true
  optimization_level: 2

processing:
  pipeline_type: "dual_channel"
  async_processing: true
  memory_optimization: false
  gpu_utilization_target: 90
  temperature_monitoring: true
  max_temperature: 80
  
  # Optimizaciones específicas
  tensorrt_precision: "fp16"
  cuda_graphs: true
  memory_pooling: true
  gradient_accumulation: 1

output:
  directory: "data/output"
  filename_pattern: "{video_name}_dual_channel_{timestamp}"
  save_intermediate: true
  compression: "lzw"
  max_file_size: 40  # MB 