model:
  name: "videomae-large"  # Modelo más potente para MVP-2
  device: "cuda"
  precision: "fp16"
  enable_compilation: true  # torch.compile optimization
  cache_models: true

limits:
  max_resolution: 1080  # Resolución más alta para MVP-2
  max_duration: 120     # Duración extendida
  max_file_size: 250    # Tamaño de archivo mayor
  allowed_formats: ["mp4", "avi", "mov", "webm", "mkv"]
  concurrent_requests: 5  # Para API

processing:
  adaptive_stride: true
  min_stride: 2
  max_stride: 12
  batch_size: 4  # Procesamiento en lotes
  temporal_smoothing: true  # Coherencia temporal
  multi_scale_attention: true  # Atención en múltiples escalas

gif:
  fps: 8  # FPS más alto
  max_frames: 30
  optimization_level: 3
  overlay_style: "heatmap"
  overlay_intensity: 0.65
  enable_preview_grid: true
  
attention:
  styles: ["heatmap", "highlight", "glow", "pulse"]
  temporal_consistency: 0.8  # Factor de coherencia temporal
  attention_threshold: 0.1   # Umbral mínimo de atención

api:
  host: "0.0.0.0"
  port: 8000
  workers: 2
  max_request_size: 300  # MB
  request_timeout: 300   # seconds
  enable_cors: true
  cors_origins: ["*"]

metrics:
  track_performance: true
  mlflow_uri: "http://localhost:5000"
  detailed_logging: true
  export_attention_maps: false  # Para debugging
  
cache:
  enable_model_cache: true
  cache_size_gb: 8
  cache_ttl: 3600  # seconds

security:
  validate_mime_type: true
  scan_for_threats: false
  rate_limiting: true
  max_requests_per_minute: 30
  
ui:
  streamlit_port: 8501
  enable_real_time_preview: true
  max_upload_size: 250  # MB

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"
  log_file: "logs/vitgif.log"
  max_log_size: "50MB"
  backup_count: 3 